# Generated by Django 5.2.6 on 2025-09-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('authors', models.CharField(help_text="Formato sugerido: 'Apellido, Nombre; Apellido2, Nombre2'", max_length=512)),
                ('pub_year', models.PositiveIntegerField(blank=True, null=True)),
                ('subjects_input', models.TextField(blank=True, help_text="Temas separados por ';' (ej. 'Educación; Metodología de la investigación')")),
                ('cutter1', models.CharField(blank=True, max_length=16)),
                ('cutter2', models.CharField(blank=True, max_length=16)),
                ('call_lcc', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
