# Generated by Django 5.2.6 on 2025-09-22 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliographicrecord',
            name='lcc_code',
            field=models.CharField(blank=True, db_index=True, help_text='Código de la Clasificación de la Library of Congress.', max_length=32, null=True, validators=[django.core.validators.RegexValidator(message="Formato LCC inválido (ej. 'QA76.73 .P98 2023').", regex='^[A-Z]{1,3}\\s?\\d{1,4}(\\.\\d+)?(\\s?[A-Z]\\d+)?(\\s?\\.\\w+)?(\\s?\\d{4})?$')], verbose_name='Clasificación LCC'),
        ),
        migrations.AddField(
            model_name='bibliographicrecord',
            name='lcc_source',
            field=models.CharField(blank=True, help_text='Origen: heurística, asignación manual, importación, etc.', max_length=64, null=True),
        ),
    ]
