# Generated by Django 5.2.6 on 2025-09-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bibliographicrecord_lcc_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='iccn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='isbn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bibliographicrecord',
            name='issn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
