# Generated by Django 5.2.6 on 2025-10-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bibliographicrecord_iccn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
